version: '3'
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    networks:
      - redis-net

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly","yes"]
    hostname: redis
    networks:
      - redis-net
  # volumes:
  #    - redis-data:/data
  port:
     - "6379:6379"
networks:
  redis-net:
#volumes:
#  redis-data:
